[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mlptrain"
description = "Machine Learning Potential Training"
authors = [{name = "Duarte Group"}]
readme = "README.md"
license = {file = "LICENSE.md"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version"]
requires-python = ">=3.8"

[project.urls]
Home = "https://github.com/duartegroup/mlp-train"
Source = "https://github.com/duartegroup/mlp-train"
