
name: Test with pytest manually

on: workflow_dispatch

jobs:
  test:
    name: Env (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.9"]
      
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
    - uses: actions/checkout@v2
        
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        auto-update-conda: true

    - name: Install
      run: |
        conda activate test
        conda install --file requirements.txt -c conda-forge
        python -m pip install . --no-deps
    - name: Test
      run: |
        pytest
