name: "Lint"

on:
  push:
    branches: [main]
  pull_request:


env:
  FORCE_COLOR: 1

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: mamba-org/setup-micromamba@v2
        with:
          # the create command looks like this:
          # `micromamba create -n test-env python=3.10 -f environment.yml`
          environment-file: environment_mace.yml
          environment-name: gha-test-env
          cache-environment: true

      - name: Run pre-commit
        run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
        env:
          SKIP: 'no-commit-to-branch'
