---
name: pytest

on:
  push:
    branches: [main]
  pull_request:

env:
  FORCE_COLOR: 1

jobs:

  test-ace:
    name: ACE (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v6

    - uses: julia-actions/setup-julia@v3
      with:
        version: '1.6'

    - uses: mamba-org/setup-micromamba@v3
      with:
        environment-file: environment_ace.yml
        environment-name: gha-test-env
        cache-environment: true
        create-args: >-
          python=${{ matrix.python-version }}

    - name: ACE install
      run: ./install_ace.sh

    - name: Test ACE
      run: pytest --cov=mlptrain -k "not test_openmm"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v6
      with:
          flags: python-${{ matrix.python-version }}-ace
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: duartegroup/mlp-train

  test-mace:
    name: MACE (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v6

    - uses: mamba-org/setup-micromamba@v3
      with:
        environment-file: environment_mace.yml
        environment-name: gha-test-env
        cache-environment: true
        create-args: >-
          python=${{ matrix.python-version }}

    - name: MACE install
      run: ./install_mace.sh

    - name: Test MACE install
      run: pytest --cov=mlptrain

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v6
      with:
          flags: python-${{ matrix.python-version }}-mace
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: duartegroup/mlp-train
